# Generated by Django 3.2.4 on 2021-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_one',
            field=models.CharField(default=True, editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_two',
            field=models.CharField(default=False, editable=False, max_length=5),
        ),
    ]
