# Generated by Django 3.2.4 on 2021-08-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210802_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_two',
        ),
    ]
