# Generated by Django 3.2.4 on 2021-08-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210802_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default='NO Category', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='App.category'),
        ),
    ]
